set(_CATKIN_CURRENT_PACKAGE "my_pcl_tutorial")
set(my_pcl_tutorial_VERSION "0.0.0")
set(my_pcl_tutorial_MAINTAINER "bc <bc@todo.todo>")
set(my_pcl_tutorial_PACKAGE_FORMAT "1")
set(my_pcl_tutorial_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all-dev")
set(my_pcl_tutorial_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(my_pcl_tutorial_BUILDTOOL_DEPENDS "catkin")
set(my_pcl_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(my_pcl_tutorial_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(my_pcl_tutorial_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "libpcl-all")
set(my_pcl_tutorial_TEST_DEPENDS )
set(my_pcl_tutorial_DOC_DEPENDS )
set(my_pcl_tutorial_DEPRECATED "")